name: Azure Policy Compliance Scan

on:
  pull_request:
    branches:
      - main

jobs:
  azure_policy_compliance_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/CLI@v1
        with:
          inlineScript: echo "Azure CLI setup complete"

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SERVICEPRINCIPAL }}

      - name: Run Azure Policy Compliance Scan
        run: |
          az policy state list --query "[?complianceState=='NonCompliant']" > policy_compliance_results.json

      - name: Upload scan results
        uses: actions/upload-artifact@v3
        with:
          name: policy-compliance-results
          path: policy_compliance_results.json